redis:
  image: redis

initializer:
  build: ./hikewithben_initialize_redis
  env_file: .env
  links:
    - redis

search:
  build: ./hikewithben_search
  env_file: .env
  ports:
    - "80:80"
  links:
    - redis

